### PR TITLE
Added Python to Curriculum

### PR DESCRIPTION
**Pull request by prachijustin**
#4

### CODE REVIEW

**Comment by itaditya** [comment]
@prachijustin the topics to cover should be so that people can get internship by learning about those topics. Right now the topics you have added looks like the table of contents of a book on beginner Python. Take a look at how topics are listed under JavaScript and others.

**Comment by prachijustin** [comment]
Sorry if my PR didn't completed the issue raised. I added only the topics that are required as a beginner in Python. For an internship as well, I have to add more topics like OOPs, DS with python as well. Django and Flask can be added too. As this is my first contribution towards open source and I am new to it, I request you to remove the *invalid* label. I will again work on this. Thanks.

**Comment by itaditya** [comment]
@prachijustin it would be unfair for others if this PR is accepted for Hacktoberfest. I'm sorry I can't accept this PR. But if you are new to OSS, this project https://github.com/itaditya/python-calculator/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc would be more suitable for you to contribute to. It's a Python CLI calculator.

**Comment by itaditya** [comment]
Let me know if you need any help with that project.

**Pull request closed without merging**
